<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net7.0;net9.0;net10.0</TargetFrameworks>
    <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'!='net7.0'">
    <PackageReference Include="FluentAssertions" Version="8.8.0"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1"/>
    <PackageReference Include="NUnit" Version="4.4.0"/>
    <PackageReference Include="NUnit3TestAdapter" Version="6.0.1"/>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net7.0'">
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mutators\Mutators.csproj" />
  </ItemGroup>

</Project>
